baseURL = 'https://shinji-hongo.github.io/hongo-tech-articles/'
languageCode = 'ja'
title = 'Hongo Tech Articles'
theme = 'blowfish'
publishDir = "docs"

[outputs]
  home = ["HTML", "JSON", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
