theme = "blowfish"
baseURL = "https://hongo-tech-articles.pages.dev/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "本郷工業 技術ブログ"
publishDir = "public"
googleAnalytics = "G-NZV4DM4GN5"

enableRobotsTXT = true
summaryLength = 30
hasCJKLanguage = true

buildDrafts = false
buildFuture = false

enableEmoji = true

[outputs]
  home = ["HTML", "JSON", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"
  category = "categories"
